name: Microservices .NET CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore CleanArchitectureWithCQRS.sln

      - name: Build solution
        run: dotnet build CleanArchitectureWithCQRS.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test CleanArchitectureWithCQRS.sln --no-build --configuration Release

      - name: Build Employee Docker image
        run: docker build -t employee-service:latest -f MyApI.API/Dockerfile .

      - name: Build Department Docker image
        run: docker build -t department-service-ciimage:latest -f MyDepartment.API/Dockerfile .

      - name: Build Payroll Docker image
        run: docker build -t payroll-service-ciimage:latest -f Payroll.API/Dockerfile .

      - name: Build notification Docker image
        run: docker build -t notification-service-ciimage:latest -f Notification.API/Dockerfile .

