name: Microservices .NET CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore CleanArchitectureWithCQRS.sln

      - name: Build solution
        run: dotnet build CleanArchitectureWithCQRS.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test CleanArchitectureWithCQRS.sln --no-build --configuration Release

      - name: Build Employee Docker image
        run: docker build -t employee-service:latest -f MyApI.API/Dockerfile .

      - name: Build Department Docker image
        run: docker build -t department-service-ciimage:latest -f MyDepartment.API/Dockerfile .

      - name: Build Payroll Docker image
        run: docker build -t payroll-service-ciimage:latest -f Payroll.API/Dockerfile .

      - name: Build notification Docker image
        run: docker build -t notification-service-ciimage:latest -f Notification.API/Dockerfile .

#this is below is login credencial for docker hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

#this is below is docker tag for images to add into docker hub

      - name: Tag Employee image
        run: docker tag employee-service:latest ${{ secrets.DOCKER_USERNAME }}/employee-service-latest

      - name: Tag Department image
        run: docker tag department-service-ciimage:latest ${{ secrets.DOCKER_USERNAME }}/department-service-latest

      - name: Tag Payroll image
        run: docker tag payroll-service-ciimage:latest ${{ secrets.DOCKER_USERNAME }}/payroll-service-latest

      - name: Tag Notification image
        run: docker tag notification-service-ciimage:latest ${{ secrets.DOCKER_USERNAME }}/notification-service-latest

#This is below is push images into docker hub repository

      - name: Push Employee image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/employee-service-latest

      - name: Push Department image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/department-service-latest

      - name: Push Payroll image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/payroll-service-latest

      - name: Push Notification image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/notification-service-latest